Ekspanderende brødsmulesti på mobil, som på spinnsyn
navikt/sykepengesok pull request #205
Opened 2020-10-12 11:52 UTC by kjarbr

2020-10-13 09:25 UTC, heyvard requested changes
URLene blir ikke riktig

2020-10-13 11:22 UTC, kjarbr commented
Korrigert test på om url-en er ekstern.

2020-10-13 11:59 UTC, heyvard requested changes

2020-10-13 11:59 UTC, heyvard commented on src/components/brodsmuler/brodsmuler.tsx
> +    const erEkstern = sti && sti.startsWith('http')
dette funker fortsatt ikke for /dittnav . Du må vel kanskje dra den helt ut og bruke hele urlen som jeg gjorde i spinnsyn-frontend

2020-10-14 09:43 UTC, heyvard approved these changes
👍

2020-10-14 09:57 UTC, merged