Erstatter syfoapi med syfosoknad-proxy
navikt/sykepengesok pull request #207
Opened 2020-11-10 14:12 UTC by golshidb93

2020-11-10 15:20 UTC, kulsveen approved these changes

2020-11-10 16:10 UTC, heyvard requested changes

2020-11-10 16:10 UTC, heyvard commented on src/components/endreknapp/endreknapp.tsx
> +        korrigerSoknad.fetch(env.syfosoknadProxyRoot + `/syfosoknad/api/soknader/${valgtSoknad!.id}/korriger`, {
her må /syfosoknad fjernes

2020-11-11 10:10 UTC, heyvard approved these changes

2020-11-12 07:49 UTC, merged