Labs nye lenker
navikt/sykepengesok pull request #458
Opened 2022-03-14 10:56 UTC by kjarbr

2022-03-16 10:19 UTC, kulsveen requested changes

2022-03-16 10:19 UTC, kulsveen commented on src/components/soknad-intro/personvern-les-mer.tsx
> +                    <button type="button" className="no-border navds-link" onClick={() => setAapen(false)}>
Denne har grå bakgrunn

2022-03-16 10:19 UTC, kulsveen commented on src/components/sporsmal/typer/perioder.tsx
> +            <button role="link" className="lenkeknapp navds-link--small" onClick={leggTilPeriode}>
Tror ikke denne navds-link--small gir noe styling

2022-03-16 11:00 UTC, kjarbr commented on src/components/soknad-intro/personvern-les-mer.tsx
> +                    <button type="button" className="no-border navds-link" onClick={() => setAapen(false)}>
Ikke nå lenger.

2022-03-16 11:00 UTC, kjarbr commented on src/components/sporsmal/typer/perioder.tsx
> +            <button role="link" className="lenkeknapp navds-link--small" onClick={leggTilPeriode}>
Nei, jeg glemte å fjerne den.

2022-03-21 08:36 UTC, kulsveen approved these changes

2022-03-21 08:37 UTC, merged